<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= $title ?></title>

    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/custom.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">StudList</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item <?=($current_page == 'index') ? 'active' : '' ?>" >
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item <?=($current_page == 'reg') ? 'active' : '' ?>" >
                    <a class="nav-link" href="/register.php">Регистрация</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="index.php" method="get">
                <input class="form-control mr-sm-2" type="text" placeholder="Поиск студентов" aria-label="Search" name="search">
                <button class="btn btn-success my-2 my-sm-0" type="submit">Найти</button>
            </form>
        </div>
    </nav>