<?php include_once "header.phtml"; ?>

<main role="main" class="container">

    <div class="starter-template">
        <?php if ($notification) : ?>
            <div class="alert alert-success col-sm-8 offset-sm-2 text-left" role="alert">
                <?= $notification ?>
            </div>
        <?php endif; ?>
        <h1><?= $title ?></h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">
                        Имя
                        <a href="<?= View::get_sort_link('name', false) ?>"> ▼</a>
                        <a href="<?= View::get_sort_link('name', true) ?>"> ▲</a>
                    </th>
                    <th scope="col">
                        Фамилия
                        <a href="<?= View::get_sort_link('surname', false) ?>"> ▼</a>
                        <a href="<?= View::get_sort_link('surname', true) ?>"> ▲</a>
                    </th>
                    <th scope="col">
                        Номер группы
                        <a href="<?= View::get_sort_link('group_number', false) ?>"> ▼</a>
                        <a href="<?= View::get_sort_link('group_number', true) ?>"> ▲</a>
                    </th>
                    <th scope="col">
                        Кол-во баллов
                        <a href="<?= View::get_sort_link('exam_score', false) ?>"> ▼</a>
                        <a href="<?= View::get_sort_link('exam_score', true) ?>"> ▲</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user) : ?>
                    <tr>
                        <td><?= htmlspecialchars($user->name) ?></td>
                        <td><?= htmlspecialchars($user->surname) ?></td>
                        <td><?= htmlspecialchars($user->group_number) ?></td>
                        <td><?= htmlspecialchars($user->exam_score) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if($paginator->enabled): ?>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <?php foreach($paginator->get_total_pages_array() as $page): ?>
                    <li class="page-item <?=($page == $paginator->current_page) ? 'active' : ''?>">
                        <a class="page-link" href="<?=View::get_page_link($page)?>"><?=$page?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    <?php endif; ?>



</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

</html>