<?php include_once "header.phtml"; ?>

<main role="main" class="container">

    <div class="starter-template">
        <?php if ($notification) : ?>
            <div class="alert alert-success col-sm-8 offset-sm-2 text-left" role="alert">
                <?= $notification ?>
            </div>
        <?php endif; ?>
        <h1><?= $title ?></h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Номер группы</th>
                    <th scope="col">Баллов</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user) : ?>
                    <tr>
                        <td><?= $user->name ?></td>
                        <td><?= $user->surname ?></td>
                        <td><?= $user->group_number ?></td>
                        <td><?= $user->exam_score ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

</html>