<?php include_once "header.phtml"; ?>

<main role="main" class="container">
    <div class="starter-template">
        <?php foreach ($errors as $error) : ?>
            <div class="alert alert-danger col-sm-8 offset-sm-2 text-left" role="alert">
                Ошибка: <?= $error ?>
            </div>
        <?php endforeach; ?>

        <h1><?= $title ?></h1>
        <div class="container regform">
            <form action="reg.php" method="post">
                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="name">Имя</label>
                        <input type="text" class="form-control" placeholder="Введите ваше имя" id="name" name="name" value="<?= $name ?>" pattern="[а-яёa-zА-ЯЁA-Z-'\s]+" title="Можно ввести буквы, пробел и символы ' -" required>
                    </div>
                    <div class="col-sm-6">
                        <label for="surname">Фамилия</label>
                        <input type="text" class="form-control" placeholder="Введите вашу фамилию" id="surname" name="surname" value="<?= $surname ?>" pattern="[а-яёa-zА-ЯЁA-Z-'\s]+" title="Можно ввести буквы, пробел и символы ' -" required>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-sm-6">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" placeholder="Введите ваш email" id="email" name="email" value="<?= $email ?>" required>
                    </div>
                    <div class="col-sm-3">
                        <label for="group_number">Номер группы</label>
                        <input type="text" class="form-control" placeholder="Группа" id="group_number" name="group_number" value="<?= $group_number ?>" pattern="[а-яёa-zА-ЯЁA-Z0-9]+" title="Можно ввести только буквы и цифры" required>
                        <small class="form-text text-muted">От 2 до 5 символов</small>
                    </div>
                    <div class="col-sm-3">
                        <label for="birth_year">Год рождения</label>
                        <input type="number" class="form-control" id="birth_year" name="birth_year" min="1901" max="2019" value="2000" value="<?= $birth_year ?>" required> 
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-sm-2">
                        <label for="exampleRadios1">Ваш пол</label>

                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="gender" id="exampleRadios1" value="male" <?= ($gender == User::GENDER_MALE) ? 'checked' : '' ?> >
                            <label class="form-check-label" for="exampleRadios1">
                                Мужской
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="gender" id="exampleRadios2" value="female" <?= ($gender == User::GENDER_FEMALE) ? 'checked' : '' ?>>
                            <label class="form-check-label" for="exampleRadios2">
                                Женский
                            </label>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <label for="exam_score">Количество баллов</label>
                        <input type="text" class="form-control" placeholder="Баллы" id="exam_score" name="exam_score" value="<?= $exam_score ?>" pattern="[0-9]+" title="Можно ввести только цифры" required>
                    </div>

                    <div class="col-sm-3 ">
                        <label for="place">Откуда вы?</label>

                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="place" id="exampleRadios1" value="local" <?= ($place == User::PLACE_LOCAL) ? 'checked' : '' ?>>
                            <label class="form-check-label" for="exampleRadios1">
                                Местный
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="place" id="exampleRadios2" value="nonlocal" <?= ($place == User::PLACE_NONLOCAL) ? 'checked' : '' ?>>
                            <label class="form-check-label" for="exampleRadios2">
                                Иногородний
                            </label>
                        </div>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-sm-6 offset-sm-3">
                        <button type="submit" class="btn btn-primary btn-bg sendbtn">Отправить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

</html>