<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Регистрация студента</title>

    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/custom.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">StudList</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/register.php">Регистрация</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Поиск студентов" aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0" type="submit">Найти</button>
            </form>
        </div>
    </nav>

    <main role="main" class="container">

        <div class="starter-template">
            <h1>Форма регистрации студента</h1>
            <div class="container regform">
                <form action="register.php" method="post">
                    <div class="row form-group">
                        <div class="col-sm-6">
                            <label for="name">Имя</label>
                            <input type="text" class="form-control" placeholder="Введите ваше имя" id="name" name="name">
                        </div>
                        <div class="col-sm-6">
                            <label for="surname">Фамилия</label>
                            <input type="text" class="form-control" placeholder="Введите вашу фамилию" id="surname" name="surname">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-sm-6">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" placeholder="Введите ваш email" id="email" name="email">
                        </div>
                        <div class="col-sm-3">
                            <label for="group_number">Номер группы</label>
                            <input type="text" class="form-control" placeholder="Группа" id="group_number" name="group_number">
                            <small class="form-text text-muted">От 2 до 5 символов</small>
                        </div>
                        <div class="col-sm-3">
                            <label for="birth_year">Год рождения</label>
                            <input type="number" class="form-control" id="birth_year" name="birth_year" min="1901" max="2019" value="2000">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-sm-2">
                            <label for="exampleRadios1">Ваш пол</label>

                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="exampleRadios1" value="male" checked>
                                <label class="form-check-label" for="exampleRadios1">
                                    Мужской
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="exampleRadios2" value="female">
                                <label class="form-check-label" for="exampleRadios2">
                                    Женский
                                </label>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <label for="exam_score">Количество баллов</label>
                            <input type="text" class="form-control" placeholder="Баллы" id="grexam_score" name="grexam_score">
                        </div>

                        <div class="col-sm-3 ">
                            <label for="place">Откуда вы?</label>

                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="place" id="exampleRadios1" value="local" checked>
                                <label class="form-check-label" for="exampleRadios1">
                                    Местный
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="place" id="exampleRadios2" value="nonlocal">
                                <label class="form-check-label" for="exampleRadios2">
                                    Иногородний
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-sm-6 offset-sm-3">
                            <button type="submit" class="btn btn-primary btn-bg sendbtn" >Отправить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </main><!-- /.container -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

</html>